In [1]:
import pandas as pd

In [3]:
data=pd.DataFrame([5,6,7,4,8])
data

   0
0  5
1  6
2  7
3  4
4  8

In [6]:
data=pd.DataFrame([[5,6,7,4,8],[9,1,2,1,5]])
data

   0  1  2  3  4
0  5  6  7  4  8
1  9  1  2  1  5

In [8]:
data=pd.DataFrame([[5,6,7,4,8],[9,1,2,1,5]],columns=['a','b','c','d','e'],index=['first','second'])
data

        a  b  c  d  e
first   5  6  7  4  8
second  9  1  2  1  5

In [9]:
data.shape

(2, 5)

In [10]:
data.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [11]:
data.index

Index(['first', 'second'], dtype='object')

In [13]:
data.values

array([[5, 6, 7, 4, 8],
       [9, 1, 2, 1, 5]])

In [17]:
D1={
    "ID":[1001,1002,1003,1004,1005],
    "NAME":["COOLIE", "VIKRAM", "ROLEX","LEO","DILLI"],
    "SCORE":[151,250,369,145,420]
}
Y=pd.DataFrame(D1)
Y

     ID    NAME  SCORE
0  1001  COOLIE    151
1  1002  VIKRAM    250
2  1003   ROLEX    369
3  1004     LEO    145
4  1005   DILLI    420

In [20]:
D2=[
    ("COOLIE",151),
    ("VIKRAM",250),
    ("ROLEX",369),
    ("LEO",145),
    ("DILLI",420)
]
Y=pd.DataFrame(D2,columns=["NAME","SCORE"])
Y

     NAME  SCORE
0  COOLIE    151
1  VIKRAM    250
2   ROLEX    369
3     LEO    145
4   DILLI    420

In [23]:
D3={
    "ID":pd.Series([6,7,8,9]),
    "NAME":pd.Series(["COOLIE","VIKRAM","ROLEX","LEO"]),
    "SCORE":pd.Series([151,250,369,145])
}
Y=pd.DataFrame(D3)
Y

   ID    NAME  SCORE
0   6  COOLIE    151
1   7  VIKRAM    250
2   8   ROLEX    369
3   9     LEO    145

In [30]:
import numpy as np
pd.DataFrame(np.random.randint(4,8,(4,4)),columns='c1 c2 c3 c4'.split(),index='r1 r2 r3 r4'.split())

    c1  c2  c3  c4
r1   4   5   7   6
r2   4   4   4   6
r3   7   5   4   7
r4   6   4   6   7

In [36]:
import pandas as pd
D4=pd.read_csv("/content/Superstore.csv",encoding="latin1")
D4.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,2698,CA-2016-145317,3/18/2016,3/23/2016,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216.0,South Updated,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784
1,6827,CA-2018-118689,10/2/2018,10/9/2018,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
2,8154,CA-2019-140151,3/23/2019,3/25/2019,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
3,2624,CA-2019-127180,10/22/2019,10/24/2019,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
4,4191,CA-2019-166709,11/17/2019,11/22/2019,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856

In [37]:
D4.shape

(9994, 21)

In [39]:
D4.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [42]:
D4.index

RangeIndex(start=0, stop=9994, step=1)

In [44]:
D4.iloc[0:3,0:4]

   Row ID        Order ID Order Date  Ship Date
0    2698  CA-2016-145317  3/18/2016  3/23/2016
1    6827  CA-2018-118689  10/2/2018  10/9/2018
2    8154  CA-2019-140151  3/23/2019  3/25/2019

In [45]:
D4.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [46]:
D4[['Order ID','Segment']]

            Order ID      Segment
0     CA-2016-145317  Home Office
1     CA-2018-118689    Corporate
2     CA-2019-140151     Consumer
3     CA-2019-127180  Home Office
4     CA-2019-166709     Consumer
...              ...          ...
9989  US-2016-152723    Corporate
9990  CA-2016-112403     Consumer
9991  CA-2018-168361    Corporate
9992  CA-2019-124114    Corporate
9993  US-2019-102288     Consumer

[9994 rows x 2 columns]

In [47]:
D4[['Order ID','Segment']].head(6)

         Order ID      Segment
0  CA-2016-145317  Home Office
1  CA-2018-118689    Corporate
2  CA-2019-140151     Consumer
3  CA-2019-127180  Home Office
4  CA-2019-166709     Consumer
5  CA-2018-117121     Consumer

In [48]:
D4[['Order ID','Segment']].tail()

            Order ID    Segment
9989  US-2016-152723  Corporate
9990  CA-2016-112403   Consumer
9991  CA-2018-168361  Corporate
9992  CA-2019-124114  Corporate
9993  US-2019-102288   Consumer

In [68]:
D4.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [70]:
D4.values

array([[2698, 'CA-2016-145317', '3/18/2016', ..., 6, 0.5, -1811.0784],
       [6827, 'CA-2018-118689', '10/2/2018', ..., 5, 0.0, 8399.976],
       [8154, 'CA-2019-140151', '3/23/2019', ..., 4, 0.0, 6719.9808],
       ...,
       [8659, 'CA-2018-168361', '6/21/2018', ..., 1, 0.8, -1.3376],
       [9293, 'CA-2019-124114', '3/2/2019', ..., 1, 0.8, -0.9452],
       [4102, 'US-2019-102288', '6/19/2019', ..., 1, 0.8, -1.11]],
      dtype=object)

In [86]:
customers=pd.DataFrame({
    "Customer_ID":[6,3,4,3,8],
    "Customer_Name":["AB,CD","EF,GH","IJ,KL","MN,OP","PQ,QR"],
    "Location":["MUMBAI","PUNE","BANGALORE","DELHI","MUMBAI"],
})
print(customers)

   Customer_ID Customer_Name   Location
0            6         AB,CD     MUMBAI
1            3         EF,GH       PUNE
2            4         IJ,KL  BANGALORE
3            3         MN,OP      DELHI
4            8         PQ,QR     MUMBAI

In [87]:
orders=pd.DataFrame({
    "Order_ID":[101,102,103,104,105],
    "Customer_ID":[1,2,3,5,5],
    "Product":["CICSO","CANNON","HP","SANYO","OKIDATA"]

  })
print(orders)

   Order_ID  Customer_ID  Product
0       101            1    CICSO
1       102            2   CANNON
2       103            3       HP
3       104            5    SANYO
4       105            5  OKIDATA

In [82]:
inner=pd.merge(customers,orders,on="Customer_ID",how="inner")
inner

   Customer_ID Customer_Name   Location  Order_ID  Product
0            1         AB,CD     MUMBAI       101    CICSO
1            2         EF,GH       PUNE       102   CANNON
2            3         IJ,KL  BANGALORE       103       HP
3            4         MN,OP      DELHI       104    SANYO
4            5         PQ,QR     MUMBAI       105  OKIDATA

In [85]:
inner=pd.merge(customers,orders,on="Customer_ID",how="inner")
inner

   Customer_ID Customer_Name   Location  Order_ID  Product
0            1         AB,CD     MUMBAI       101    CICSO
1            1         EF,GH       PUNE       101    CICSO
2            3         IJ,KL  BANGALORE       103       HP
3            5         PQ,QR     MUMBAI       104    SANYO
4            5         PQ,QR     MUMBAI       105  OKIDATA

In [88]:
inner=pd.merge(customers,orders,on="Customer_ID",how="inner")
inner

   Customer_ID Customer_Name Location  Order_ID Product
0            3         EF,GH     PUNE       103      HP
1            3         MN,OP    DELHI       103      HP