In [2]:
import pandas as pd

In [3]:
import numpy as np
D1={
    "ID":[1001,np.nan,1003,1004,1005],
    "NAME":["COOLIE", "VIKRAM", "ROLEX","LEO","DILLI"],
    "SCORE":[np.nan,250,369,np.nan,420]
}
Y=pd.DataFrame(D1)
Y

       ID    NAME  SCORE
0  1001.0  COOLIE    NaN
1     NaN  VIKRAM  250.0
2  1003.0   ROLEX  369.0
3  1004.0     LEO    NaN
4  1005.0   DILLI  420.0

In [4]:
Y.dropna(axis=0,how='any')

       ID   NAME  SCORE
2  1003.0  ROLEX  369.0
4  1005.0  DILLI  420.0

In [5]:
Y.dropna(axis=0,how='all')

       ID    NAME  SCORE
0  1001.0  COOLIE    NaN
1     NaN  VIKRAM  250.0
2  1003.0   ROLEX  369.0
3  1004.0     LEO    NaN
4  1005.0   DILLI  420.0

In [6]:
Y

       ID    NAME  SCORE
0  1001.0  COOLIE    NaN
1     NaN  VIKRAM  250.0
2  1003.0   ROLEX  369.0
3  1004.0     LEO    NaN
4  1005.0   DILLI  420.0

In [7]:
D1={
    "ID":[1001,np.nan,1003,1004,1005],
    "NAME":["COOLIE", "VIKRAM", "ROLEX","LEO","DILLI"],
    "SCORE":[np.nan,250,369,np.nan,420],
    "DAYS":[np.nan,600,1000,365,np.nan]
}
Y=pd.DataFrame(D1)
Y

       ID    NAME  SCORE    DAYS
0  1001.0  COOLIE    NaN     NaN
1     NaN  VIKRAM  250.0   600.0
2  1003.0   ROLEX  369.0  1000.0
3  1004.0     LEO    NaN   365.0
4  1005.0   DILLI  420.0     NaN

In [8]:
Y['SCORE'].fillna(300)

0    300.0
1    250.0
2    369.0
3    300.0
4    420.0
Name: SCORE, dtype: float64

In [9]:
Y

       ID    NAME  SCORE    DAYS
0  1001.0  COOLIE    NaN     NaN
1     NaN  VIKRAM  250.0   600.0
2  1003.0   ROLEX  369.0  1000.0
3  1004.0     LEO    NaN   365.0
4  1005.0   DILLI  420.0     NaN

In [11]:
Y['SCORE'].fillna(300,inplace=True)

/tmp/ipython-input-1419385828.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Y['SCORE'].fillna(300,inplace=True)

In [10]:
Y

       ID    NAME  SCORE    DAYS
0  1001.0  COOLIE    NaN     NaN
1     NaN  VIKRAM  250.0   600.0
2  1003.0   ROLEX  369.0  1000.0
3  1004.0     LEO    NaN   365.0
4  1005.0   DILLI  420.0     NaN

In [12]:
D1={
    "ID":[1001,np.nan,1003,1004,1005],
    "NAME":["COOLIE", "VIKRAM", "ROLEX","LEO","DILLI"],
    "SCORE":[np.nan,250,369,np.nan,420],
    "DAYS":[np.nan,600,1000,365,np.nan]
}
Y=pd.DataFrame(D1)
Y

       ID    NAME  SCORE    DAYS
0  1001.0  COOLIE    NaN     NaN
1     NaN  VIKRAM  250.0   600.0
2  1003.0   ROLEX  369.0  1000.0
3  1004.0     LEO    NaN   365.0
4  1005.0   DILLI  420.0     NaN

In [13]:
Y['SCORE'].fillna(Y['SCORE'].median())

0    369.0
1    250.0
2    369.0
3    369.0
4    420.0
Name: SCORE, dtype: float64

In [14]:
Y

       ID    NAME  SCORE    DAYS
0  1001.0  COOLIE    NaN     NaN
1     NaN  VIKRAM  250.0   600.0
2  1003.0   ROLEX  369.0  1000.0
3  1004.0     LEO    NaN   365.0
4  1005.0   DILLI  420.0     NaN

In [17]:
Y['SCORE'].fillna(Y['SCORE'].median(),inplace=True)

/tmp/ipython-input-4273380620.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Y['SCORE'].fillna(Y['SCORE'].median(),inplace=True)

In [135]:
Y

       ID    NAME  SCORE    DAYS
0  1001.0  COOLIE  290.0     NaN
1     NaN  VIKRAM  250.0   600.0
2  1003.0   ROLEX  369.0  1000.0
3  1004.0     LEO  290.0   365.0
4  1005.0   DILLI  420.0     NaN

In [19]:
D1={
    "ID":[1001,np.nan,1003,1004,1005],
    "NAME":["COOLIE", "VIKRAM", "ROLEX","LEO","DILLI"],
    "SCORE":[np.nan,250,369,np.nan,420],
    "DAYS":[np.nan,600,1000,365,np.nan]
}
Y=pd.DataFrame(D1)
Y

       ID    NAME  SCORE    DAYS
0  1001.0  COOLIE    NaN     NaN
1     NaN  VIKRAM  250.0   600.0
2  1003.0   ROLEX  369.0  1000.0
3  1004.0     LEO    NaN   365.0
4  1005.0   DILLI  420.0     NaN

In [20]:
Y['DAYS'].fillna(method='ffill')

/tmp/ipython-input-3828340068.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  Y['DAYS'].fillna(method='ffill')

0       NaN
1     600.0
2    1000.0
3     365.0
4     365.0
Name: DAYS, dtype: float64

In [21]:
Y['DAYS'].fillna(method='bfill')

/tmp/ipython-input-3540781961.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  Y['DAYS'].fillna(method='bfill')

0     600.0
1     600.0
2    1000.0
3     365.0
4       NaN
Name: DAYS, dtype: float64

In [22]:
Y

       ID    NAME  SCORE    DAYS
0  1001.0  COOLIE    NaN     NaN
1     NaN  VIKRAM  250.0   600.0
2  1003.0   ROLEX  369.0  1000.0
3  1004.0     LEO    NaN   365.0
4  1005.0   DILLI  420.0     NaN

In [23]:
Y.isna()

      ID   NAME  SCORE   DAYS
0  False  False   True   True
1   True  False  False  False
2  False  False  False  False
3  False  False   True  False
4  False  False  False   True

In [24]:
Y.isna().sum()

ID       1
NAME     0
SCORE    2
DAYS     2
dtype: int64

In [25]:
Y.shape[0]

5

In [26]:
Null_table=(Y.isna().sum()/Y.shape[0])*100

In [27]:
Null_table

ID       20.0
NAME      0.0
SCORE    40.0
DAYS     40.0
dtype: float64

In [28]:
Null_table[Null_table<30]

ID      20.0
NAME     0.0
dtype: float64

In [29]:
Null_table[Null_table<30].index

Index(['ID', 'NAME'], dtype='object')

In [30]:
Null_table[Null_table>30]

SCORE    40.0
DAYS     40.0
dtype: float64

In [31]:
Null_table[Null_table>30].index

Index(['SCORE', 'DAYS'], dtype='object')

In [32]:
Y.drop(['SCORE','DAYS'],axis=1)

       ID    NAME
0  1001.0  COOLIE
1     NaN  VIKRAM
2  1003.0   ROLEX
3  1004.0     LEO
4  1005.0   DILLI

In [ ]:
##Memory_optimization

In [49]:
D2=pd.read_excel("/content/Sample - Superstore.xlsx")
D2.head()

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,2698,CA-2016-145317,2016-03-18,2016-03-23,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216.0,South Updated,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784
1,6827,CA-2018-118689,2018-10-02,2018-10-09,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
2,8154,CA-2019-140151,2019-03-23,2019-03-25,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
3,2624,CA-2019-127180,2019-10-22,2019-10-24,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
4,4191,CA-2019-166709,2019-11-17,2019-11-22,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856

In [34]:
D2.memory_usage()

Index               132
Row ID            79952
Order ID          79952
Order Date        79952
Ship Date         79952
Ship Mode         79952
Customer ID       79952
Customer Name     79952
Segment           79952
Country/Region    79952
City              79952
State             79952
Postal Code       79952
Region            79952
Product ID        79952
Category          79952
Sub-Category      79952
Product Name      79952
Sales             79952
Quantity          79952
Discount          79952
Profit            79952
dtype: int64

In [35]:
D2.memory_usage().sum()

np.int64(1679124)

In [40]:
D2.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country/Region            object
City                      object
State                     object
Postal Code              float64
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
dtype: object

In [38]:
D2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          9994 non-null   int64
 1   Order ID        9994 non-null   object
 2   Order Date      9994 non-null   datetime64[ns]
 3   Ship Date       9994 non-null   datetime64[ns]
 4   Ship Mode       9994 non-null   object
 5   Customer ID     9994 non-null   object
 6   Customer Name   9994 non-null   object
 7   Segment         9994 non-null   object
 8   Country/Region  9994 non-null   object
 9   City            9994 non-null   object
 10  State           9994 non-null   object
 11  Postal Code     9983 non-null   float64
 12  Region          9994 non-null   object
 13  Product ID      9994 non-null   object
 14  Category        9994 non-null   object
 15  Sub-Category    9994 non-null   object
 16  Product Name    9994 non-null   object
 17  Sales           9994 non-null   float64
 18  Quantity        9994 non-null   int64
 19  Discount        9994 non-null   float64
 20  Profit          9994 non-null   float64
dtypes: datetime64[ns](2), float64(4), int64(2), object(13)
memory usage: 1.6+ MB

In [47]:
D2['Profit'].head()

0   -1811.0784
1    8399.9760
2    6719.9808
3    3919.9888
4    5039.9856
Name: Profit, dtype: float64

In [50]:
D2.memory_usage().sum()/(1024*1024)

np.float64(1.6013374328613281)

In [53]:
D2['Profit']=D2['Profit'].astype(np.int32)
D2['Profit'].head()

0   -1811
1    8399
2    6719
3    3919
4    5039
Name: Profit, dtype: int32

In [54]:
D2.memory_usage().sum()/(1024*1024)

np.float64(1.5632133483886719)

In [55]:
D2.select_dtypes(["int64"]).columns

Index(['Row ID', 'Quantity'], dtype='object')

In [ ]:
for col in D2.select_dtypes(["int64"]).columns:
  # col_type=D2['col'].dtype
  c_min,c_max=D2[col].min(),D2[col].max()
  if str(col_type).startswith=='int':
    if c_min>np.iinfo(np.int8).min and c_max<np.iinfo(np.int8).max:
      D2[col]=D2[col].astype(np.int8)
    elif c_min>np.iinfo(np.int16).min and c_max<np.iinfo(np.int16).max:
      D2[col]=D2[col].astype(np.int16)
    elif c_min>np.iinfo(np.int32).min and c_max<np.iinfo(np.int32).max:
      D2[col]=D2[col].astype(np.int32)
    else:
      D2[col]=D2[col].astype(np.int64)

In [87]:
c_min

1040.0

In [88]:
c_max

99301.0

In [94]:
D2.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,2698,CA-2016-145317,2016-03-18,2016-03-23,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216.0,South Updated,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811
1,6827,CA-2018-118689,2018-10-02,2018-10-09,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399
2,8154,CA-2019-140151,2019-03-23,2019-03-25,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719
3,2624,CA-2019-127180,2019-10-22,2019-10-24,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919
4,4191,CA-2019-166709,2019-11-17,2019-11-22,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039

In [96]:
Y[['SCORE','DAYS']]

   SCORE    DAYS
0    NaN     NaN
1  250.0   600.0
2  369.0  1000.0
3    NaN   365.0
4  420.0     NaN

In [128]:
Y[['SCORE','DAYS']].fillna(290,inplace=True)

/tmp/ipython-input-30455913.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Y[['SCORE','DAYS']].fillna(290,inplace=True)

In [134]:
Y[['SCORE','DAYS']]

   SCORE    DAYS
0  290.0     NaN
1  250.0   600.0
2  369.0  1000.0
3  290.0   365.0
4  420.0     NaN

In [136]:
Y

       ID    NAME  SCORE    DAYS
0  1001.0  COOLIE  290.0     NaN
1     NaN  VIKRAM  250.0   600.0
2  1003.0   ROLEX  369.0  1000.0
3  1004.0     LEO  290.0   365.0
4  1005.0   DILLI  420.0     NaN

In [137]:
Y[['SCORE','DAYS']].fillna(290,inplace=True)

/tmp/ipython-input-30455913.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Y[['SCORE','DAYS']].fillna(290,inplace=True)

In [138]:
Y[['SCORE','DAYS']]

   SCORE    DAYS
0  290.0     NaN
1  250.0   600.0
2  369.0  1000.0
3  290.0   365.0
4  420.0     NaN